providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node_modules/.bin/serve -s dist -l tcp://0.0.0.0:${PORT:-80} -l tcp://0.0.0.0:3000 -l tcp://0.0.0.0:80"
